Repository nugu-developers/nugu-ios, pull requests merged in 2019-11, with the labels that each got.

#25 Fix an issue where delegate was not called because currentMedia is nil.
  NuguCore/Classes/Business/Capability/TextToSpeech/TTSAgent.swift
Labels: bug

#26 init travis
  .travis.yml
  NuguTest/NuguCoreTest/NuguCoreTest.swift
  NuguTest/Podfile
Labels: ci/cd

#31 add travis to README
  NuguTest/NuguCoreTest/NuguCoreTest.swift
  README.md
Labels: ci/cd

#35 Modify DirectiveMedium so that TTS.Stop directive does not blocked.
  NuguCore/Classes/Business/Capability/TextToSpeech/TTSAgent+Directive.swift
Labels: bug

#37 Fix swift-lint exception
  NuguLoginKit/Classes/Network/Type1Api.swift
Labels: bug

#42 Deprecate System.Revoke directive.
  NuguCore/Classes/Business/Authorization/AuthorizationManager.swift
  NuguCore/Classes/Business/Capability/System/SystemAgent+Directive.swift
  NuguCore/Classes/Business/Capability/System/SystemAgent.swift
  NuguCore/Classes/Business/Capability/System/SystemAgentRevokeItem.swift
  NuguInterface/Classes/Authorization/AuthorizationError.swift
  NuguInterface/Classes/Capability/System/SystemAgentDelegate.swift
  NuguInterface/Classes/Capability/System/SystemRevokeReason.swift
  Sample/SampleApp-iOS/Manager/NuguCentralManager.swift
Labels: enhancement

#41 Feature/directive sequencer
  NuguClientKit/Classes/NuguClient+Coordinator.swift
  NuguCore/Classes/Business/Capability/AudioPlayer/AudioPlayerAgent+Directive.swift
  NuguCore/Classes/Business/Capability/AutomaticSpeechRecognition/ASRAgent+Directive.swift
  NuguCore/Classes/Business/Capability/Display/DisplayAgent+Directive.swift
  NuguCore/Classes/Business/Capability/Extension/ExtensionAgent+Directive.swift
  NuguCore/Classes/Business/Capability/Speaker/SpeakerAgent+Directive.swift
  NuguCore/Classes/Business/Capability/System/SystemAgent+Directive.swift
  NuguCore/Classes/Business/Capability/System/SystemAgent.swift
  NuguCore/Classes/Business/Capability/TextToSpeech/TTSAgent+Directive.swift
  NuguCore/Classes/Business/Directive/DirectiveSequencer.swift
  NuguCore/Classes/Business/Network/HTTP/Model/DownStreamData.swift
  NuguInterface/Classes/Directive/DirectiveSequenceable.swift
  NuguInterface/Classes/Directive/DirectiveTypeInfos.swift
Labels: code quality

#43 Fixes a bug that was not handled when the ASRResult was the same as b…
  NuguCore/Classes/Business/Capability/AutomaticSpeechRecognition/ASRAgent.swift
Labels: bug

#49 Update gitignore
  nugu-ios.xcodeproj/xcshareddata/xcschemes/JadeMarble.xcscheme
  nugu-ios.xcodeproj/xcshareddata/xcschemes/KeenSense.xcscheme
  nugu-ios.xcodeproj/xcshareddata/xcschemes/NuguClientKit.xcscheme
  nugu-ios.xcodeproj/xcshareddata/xcschemes/NuguCore.xcscheme
  nugu-ios.xcodeproj/xcshareddata/xcschemes/NuguInterface.xcscheme
  nugu-ios.xcodeproj/xcshareddata/xcschemes/NuguLoginKit.xcscheme
  nugu-ios.xcodeproj/xcshareddata/xcschemes/NuguUIKit.xcscheme
Labels: bug

#50 Bug/asr agent event
  NuguCore/Sources/Business/Capability/AutomaticSpeechRecognition/ASRAgent+Event.swift
Labels: bug

#51 Update readme for changing project structure
  README.md
Labels: documentation

#53 Config/proj
  .github/CODEOWNERS
  Cartfile.resolved
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#68 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/scheduled-feature.md
  nugu-ios.xcodeproj/project.pbxproj
Labels: documentation

#63 Implement PermissionAgent (#60)
  NuguCore/Sources/Business/Capability/Permission/PermissionAgent+Directive.swift
  NuguCore/Sources/Business/Capability/Permission/PermissionAgent+Event.swift
  NuguCore/Sources/Business/Capability/Permission/PermissionAgent.swift
  NuguCore/Sources/Business/Capability/Permission/PermissionAgentItem.swift
  NuguInterface/Sources/Capability/CapabilityAgentCategory.swift
  NuguInterface/Sources/Capability/Permission/PermissionAgentDelegate.swift
  NuguInterface/Sources/Capability/Permission/PermissionAgentProtocol.swift
  NuguInterface/Sources/Capability/Permission/PermissionContext.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#64 Update location agent (#19)
  NuguCore/Sources/Business/Capability/Location/LocationAgent.swift
  NuguInterface/Sources/Capability/Location/LocationAgentDelegate.swift
  NuguInterface/Sources/Capability/Location/LocationContext.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#72 Implement PermissionAgent in NuguClientKit
  NuguClientKit/Sources/NuguClient+Builder.swift
  NuguClientKit/Sources/NuguClient+Coordinator.swift
  NuguClientKit/Sources/NuguClient.swift
Labels: enhancement

#75 Update xcodeproj for ordering files
  NuguClientKit/Sources/WakeUpDetectorProtocol.swift
  NuguCore/Sources/Util/Atomic.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#79 Delete NuguApiProvider instance after calling NuguApiProvider.disconnect().
  NuguCore/Sources/Business/Network/NetworkManager.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug

#89 Stop BoundStreams before creating new instance.
  JadeMarble/Sources/TycheEpd.swift
  KeenSense/Sources/KeyWordDetector/TycheKwd.swift
  NuguClientKit/Sources/BoundStreams.swift
  NuguClientKit/Sources/EndPointDetector.swift
  NuguClientKit/Sources/KeyWordDetector.swift
  NuguClientKit/Sources/WakeUpDetectorProtocol.swift
  NuguCore/Sources/Business/Capability/AutomaticSpeechRecognition/ASRAgent.swift
  NuguCore/Sources/Core/Audio/AudioStream/AudioStream.swift
  NuguInterface/Sources/EndPointDetector/EndPointDetectable.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug

#83 Update model related location and permission agents
  NuguInterface/Sources/Capability/Location/LocationContext.swift
  NuguInterface/Sources/Capability/Permission/PermissionContext.swift
Labels: bug, enhancement

#93 Make JadeMarble & KeenSense not to be stuck in their RunLoop.
  JadeMarble/Sources/TycheEpd.swift
  KeenSense/Sources/KeyWordDetector/TycheKwd.swift
  NuguClientKit/Sources/BoundStreams.swift
Labels: bug

#97 Feature/guide web
  SampleApp/Resources/Base.lproj/Main.storyboard
  SampleApp/Sources/Const/SampleApp.swift
  SampleApp/Sources/UI/MainViewController.swift
  SampleApp/Sources/UI/WebViewController.swift
Labels: enhancement

#102 Remove timeout case in `LocationContext`
  NuguInterface/Sources/Capability/Location/LocationContext.swift
Labels: capability agent, enhancement

#98 Restart Audio data scheduler when the new data arrived in OpusPlayer.
  NuguCore/Sources/Core/OpusPlayer/OpusPlayer.swift
  NuguCore/Sources/Util/Publish.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug

#110 Update comment in files (minor)
  NuguInterface/Sources/Util/DelegateDictionary.swift
  NuguInterface/Sources/Util/DelegateSet.swift
Labels: code quality

#103 Feature/play stack control
  NuguCore/Sources/Business/Capability/AudioPlayer/AudioPlayerAgent.swift
  NuguCore/Sources/Business/Capability/AudioPlayer/AudioPlayerAgentMedia.swift
  NuguCore/Sources/Business/Capability/AudioPlayer/Display/AudioPlayerDisplayManageable.swift
  NuguCore/Sources/Business/Capability/AudioPlayer/Display/AudioPlayerDisplayManager.swift
  NuguCore/Sources/Business/Capability/Display/DisplayAgent.swift
  NuguCore/Sources/Business/Capability/TextToSpeech/TTSAgent.swift
  NuguCore/Sources/Business/Capability/TextToSpeech/TTSMedia.swift
  NuguCore/Sources/Business/PlaySync/PlaySyncInfo.swift
  NuguCore/Sources/Business/PlaySync/PlaySyncManager.swift
  NuguInterface/Sources/Capability/AudioPlayer/Display/AudioPlayerDisplayTemplate.swift
  NuguInterface/Sources/Capability/Display/DisplayTemplate.swift
  NuguInterface/Sources/PlaySync/PlaySyncManageable.swift
Labels: capability agent

#111 Add `TimeIntervallic` protocol (#106)
  NuguCore/Sources/Business/Capability/AudioPlayer/AudioPlayerAgent.swift
  NuguCore/Sources/Core/MediaPlayer/MediaPlayer.swift
  NuguCore/Sources/Core/OpusPlayer/OpusPlayer.swift
  NuguInterface/Sources/Capability/AudioPlayer/AudioPlayerAgentProtocol.swift
  NuguInterface/Sources/MediaPlayer/MediaPlayable.swift
  NuguInterface/Sources/Util/Delegate/DelegateDictionary.swift
  NuguInterface/Sources/Util/Delegate/DelegateSet.swift
  NuguInterface/Sources/Util/TimeInterval/NuguTimeInterval.swift
  NuguInterface/Sources/Util/TimeInterval/TimeIntervallic.swift
  NuguTests/TimeIntervallicTests.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#107 Apply PermissionAgentDelegate, LocationAgentDelegate
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/Manager/NuguLocationManager.swift
  SampleApp/Supporting Files/Info.plist
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#113 Feature/message interpreter
  NuguClientKit/Sources/NuguClient+Coordinator.swift
  NuguClientKit/Sources/NuguClient.swift
  NuguCore/Sources/Business/Capability/AudioPlayer/AudioPlayerAgent.swift
  NuguCore/Sources/Business/Capability/AutomaticSpeechRecognition/ASRAgent.swift
  NuguCore/Sources/Business/Capability/Display/DisplayAgent.swift
  NuguCore/Sources/Business/Capability/Extension/ExtensionAgent.swift
  NuguCore/Sources/Business/Capability/Permission/PermissionAgent.swift
  NuguCore/Sources/Business/Capability/Speaker/SpeakerAgent.swift
  NuguCore/Sources/Business/Capability/System/SystemAgent.swift
  NuguCore/Sources/Business/Capability/Text/TextAgent.swift
  NuguCore/Sources/Business/Capability/TextToSpeech/TTSAgent.swift
  NuguCore/Sources/Business/Directive/DirectiveSequencer.swift
  NuguCore/Sources/Business/Directive/DownStreamDataInterpreter.swift
  NuguCore/Sources/Business/Network/HTTP/Model/DownStreamData.swift
  NuguCore/Sources/Business/Network/NetworkManager.swift
  NuguInterface/Sources/Capability/AutomaticSpeechRecognition/ASRAgentProtocol.swift
  NuguInterface/Sources/Capability/Text/TextAgentProtocol.swift
  NuguInterface/Sources/Directive/DirectiveSequenceable.swift
  NuguInterface/Sources/Directive/DownStreamDataDelegate.swift
  NuguInterface/Sources/Directive/DownStreamDataInterpretable.swift
  NuguInterface/Sources/Directive/HandleDirectiveDelegate.swift
  NuguInterface/Sources/Directive/Model/DownStream.swift
  NuguInterface/Sources/Network/MessageReceivable.swift
  NuguInterface/Sources/Network/Model/AttachmentProtocol.swift
  NuguInterface/Sources/Network/Model/MessageHeaderProtocol.swift
  NuguInterface/Sources/Network/NetworkManageable.swift
  NuguInterface/Sources/Network/ReceiveMessageDelegate.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#116 Update FocusChannelConfigurable
  NuguClientKit/Sources/FocusChannelConfiguration.swift
  NuguClientKit/Sources/NuguClient+Coordinator.swift
  NuguInterface/Sources/Focus/FocusChannelConfigurable.swift
Labels: enhancement

#76 Remove lottie-ios and add NuguVoiceChromeAnimationView instead
  Cartfile
  Cartfile.resolved
  NuguUIKit.podspec
  NuguUIKit/Resources/LottieAnimation/01 Listening-Passive/LP.json
  NuguUIKit/Resources/LottieAnimation/02 Listening-Active/LA.json
  NuguUIKit/Resources/LottieAnimation/03 Processing/PC_01_start.json
  NuguUIKit/Resources/LottieAnimation/03 Processing/PC_02.json
  NuguUIKit/Resources/LottieAnimation/04 Speaking/SP_01_start.json
  NuguUIKit/Resources/LottieAnimation/04 Speaking/SP_02.json
  NuguUIKit/Resources/LottieAnimation/04 Speaking/SP_03_final.json
  NuguUIKit/Resources/LottieAnimation/04 Speaking/SP_none.json
  NuguUIKit/Resources/LottieAnimation/05 Error-Speaking/ESP_01_start.json
  NuguUIKit/Resources/LottieAnimation/05 Error-Speaking/ESP_02.json
  NuguUIKit/Resources/LottieAnimation/05 Error-Speaking/ESP_03_final.json
  NuguUIKit/Sources/Button/NuguButton.swift
  NuguUIKit/Sources/VoiceChrome/NuguVoiceChrome.swift
  NuguUIKit/Sources/VoiceChrome/NuguVoiceChrome.xib
  NuguUIKit/Sources/VoiceChrome/NuguVoiceChromeAnimationView.swift
  SampleApp/Sources/UI/MainViewController.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement
