Repository nugu-developers/nugu-ios, pull requests merged in 2020-10, with the labels that each got.

#559 Remove useless api during passing string to library
  JadeMarble/Sources/TycheEndPointDetectorEngine.swift
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngine.swift
Labels: crash

#571 Change Agent's state properly when `MediaPlayer` stopped by another `MediaPlayer`.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
Labels: bug

#573 `PhoneCallAgent` 1.2 (upgrade capability-agent)
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallCandidatesItem.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallRecipientIntended.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallTemplate.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent
