Repository nugu-developers/nugu-ios, pull requests merged in 2020-11, with the labels that each got.

#581 Make `KeywordSource` not possible to be set simultaniouly.
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngine.swift
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetector.swift
Labels: crash

#580 Assign and release focus synchronously.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguCore/Sources/Focus/FocusManager.swift
Labels: bug

#577 Fixes a bug where prefetch `AudioPlayer.Play`.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
Labels: bug

#582 Fixes a bug where `startWakeUpDetector` does not called.
  SampleApp/Sources/Manager/NuguCentralManager.swift
Labels: bug

#583 Make computed properties of `AudioPlayerAgent` and `TTSAgent` to be thread safe.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguCore/Sources/Util/Delegate/DelegateSet.swift
Labels: crash

#587 Carthage update script for Xcode 12
  carthage.sh
Labels: ci/cd

#592 Make codable models in `PhoneCallAgent` and `MediaPlayerAgent`
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentPlaylist.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallCandidatesItem.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallState.swift
Labels: capability agent

#590 `ASRAgent` 1.4 (upgrade capability-agent)
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRExpectSpeech.swift
Labels: capability agent

#593 Pass `Downstream.Header` instead of `DialogRequestId` to function parameter of agent delegate.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayManager.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgent.swift
  NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgent.swift
  NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgentDataSource.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundMedia.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
  NuguClientKit/Sources/Business/DialogStateAggregator.swift
  NuguCore/Sources/StreamData/Model/Downstream.swift
  NuguTests/NuguAgents/ExtensionAgentSpec.swift
  NuguTests/NuguAgents/SoundAgentSpec.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: capability agent

#584 Extends decodable public struct to conform `Codable`
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayControlPayload.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayRepeat.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayControlPayload.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayTemplate.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgentExceptionCode.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgentRevokeItem.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgentRevokeReason.swift
  NuguAgents/Sources/Directive/PlayStackControl.swift
  NuguCore/Sources/PlaySync/PlaySyncProperty.swift
Labels: capability agent

#586 Extends public struct conforming `Decodable` to conform `Codable`
  NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgentItem.swift
  NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgentItem.swift
  NuguAgents/Sources/CapabilityAgents/Session/SessionAgentItem.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundBeepName.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundMedia.swift
Labels: capability agent

#596 `MediaPlayer` 1.1 (upgrade capability-agent)
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentResult.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentSong.swift
Labels: capability agent

#597 Build project using Xcode 12 and test it on latest iOS
  .travis.yml
Labels: ci/cd

#598 Move `NCObjcExceptionCatcher` from `NuguCore` to `NuguClient`.
  NuguClientKit.podspec
  NuguClientKit/NuguClientKit.h
  NuguClientKit/Sources-ObjC/NCObjcExceptionCatcher.h
  NuguClientKit/Sources-ObjC/NCObjcExceptionCatcher.m
  NuguCore.podspec
  NuguCore/NuguCore.h
  SampleApp/Podfile.lock
  SampleApp/SampleApp.xcodeproj/project.pbxproj
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug

#600 Modify the delegate function to be called asynchronously to avoid deadlock.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguCore/Sources/Util/Delegate/DelegateSet.swift
Labels: bug

#601 Create deploy_cocoapods.yml
  .github/workflows/deploy_cocoapods.yml
Labels: ci/cd

#602 Start a timer to stop `MediaPlayer` when playback is temporarily paused.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: capability agent

#604 Add `prepareFocus` and `cancelFocus` to `FocusManageable`.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguCore/Sources/Directive/DirectiveHandleInfo.swift
  NuguCore/Sources/Focus/FocusManageable.swift
  NuguCore/Sources/Focus/FocusManager.swift
  NuguCore/Sources/Focus/FocusState.swift
  NuguTests/Mock/MockFocusManager.swift
  SampleApp/Sources/MediaPlayer/LocalTTSAgent.swift
Labels: enhancement

#606 Fix parsing error in `MediaPlayerAgent`
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentSong.swift
Labels: capability agent

#613 Pass `Downstream.Header` to function parameter of agent delegate.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayDelegate.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayManageable.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayManager.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayTemplate.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRResult.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayTemplate.swift
  SampleApp/Sources/UI/MainViewController.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#620 Add `directiveSequencerWillPrefetch` function to `DirectiveSequencerDelegate`
  NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
  NuguCore/Sources/Directive/DirectiveSequencer.swift
  NuguCore/Sources/Directive/DirectiveSequencerDelegate.swift
Labels: enhancement

#619 Fixes a bug where `playServiceId` is missing when sending `TTS` event.
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
Labels: bug

#623 Fixes a build error.
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug

#630 Fixes a bug when canceling and resuming timers for layer.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayManager.swift
  NuguCore/Sources/PlaySync/PlaySyncManager.swift
Labels: bug

#633 Pass only 1 `sessionId` for `playServiceId` in the context of `SessionAgent`. Closes #626
  NuguAgents/Sources/CapabilityAgents/Session/SessionAgent.swift
Labels: capability agent

#635 Skip attachment when last data appended.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
Labels: bug, capability agent

#634 `TextAgent` 1.5 (upgrade capability-agent)
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentRedirectPayload.swift
  SampleApp/Sources/UI/MainViewController.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#644 Fixes a build error in `SampleApp`
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug

#643 Request focus synchronously when handling `ASR.ExpectSpeech`.
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRConst.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRResult.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug, capability agent

#651 Add `init` function to initialize with `UIView`.
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: enhancement
