Repository nugu-developers/nugu-ios, pull requests merged in 2021-06, with the labels that each got.

#854 Support AudioDisplayView dark mode
  NuguUIKit/Resources/Assets.xcassets/btn_like_off.imageset/btn_like_off@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_like_off.imageset/btn_like_off@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_like_on.imageset/btn_like_on@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_like_on.imageset/btn_like_on@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_pause.imageset/btn_pause@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_pause.imageset/btn_pause@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_pause_dark.imageset/Contents.json
  NuguUIKit/Resources/Assets.xcassets/btn_pause_dark.imageset/btn_pause_dark@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_pause_dark.imageset/btn_pause_dark@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_play.imageset/btn_play@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_play.imageset/btn_play@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_play_dark.imageset/Contents.json
  NuguUIKit/Resources/Assets.xcassets/btn_play_dark.imageset/btn_play_dark@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_play_dark.imageset/btn_play_dark@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_random_off.imageset/btn_random_off@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_random_off.imageset/btn_random_off@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_random_on.imageset/btn_random_on@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_random_on.imageset/btn_random_on@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_repeat_1_on.imageset/btn_repeat_1_on@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_repeat_1_on.imageset/btn_repeat_1_on@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_repeat_off.imageset/btn_repeat_off@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_repeat_off.imageset/btn_repeat_off@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_repeat_on.imageset/btn_repeat_on@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_repeat_on.imageset/btn_repeat_on@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_next.imageset/btn_skip_next@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_next.imageset/btn_skip_next@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_next_dark.imageset/Contents.json
  NuguUIKit/Resources/Assets.xcassets/btn_skip_next_dark.imageset/btn_skip_next_dark@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_next_dark.imageset/btn_skip_next_dark@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_previous.imageset/btn_skip_previous@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_previous.imageset/btn_skip_previous@3x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_previous_dark.imageset/Contents.json
  NuguUIKit/Resources/Assets.xcassets/btn_skip_previous_dark.imageset/btn_skip_previous_dark@2x.png
  NuguUIKit/Resources/Assets.xcassets/btn_skip_previous_dark.imageset/btn_skip_previous_dark@3x.png
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayViewTheme.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.xib
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/DisplayIdleBar.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#858 Add routine related javascript methods to `NuguServiceWebView`
  NuguServiceKit/Sources/NuguServiceWebJavascriptDelegate.swift
  NuguServiceKit/Sources/NuguServiceWebView.swift
  SampleApp/Sources/UI/GuideWebViewController.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
Labels: enhancement, sample application

#853 Add `NuguThemeController` to `NuguClientKit`
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguClientKit/Sources/Presenter/NuguTheme.swift
  NuguClientKit/Sources/Presenter/NuguThemeController.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  NuguUIKit/Sources/Chips/NuguChipsButton.swift
  NuguUIKit/Sources/Chips/NuguChipsView.swift
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.swift
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.xib
  NuguUIKit/Sources/VoiceChrome/NuguVoiceChrome.swift
  NuguUtils/Sources/UserInterface/UserInterfaceUtil.swift
  SampleApp/Resources/Base.lproj/Main.storyboard
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/MainViewController.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement, sample application

#860 Notify `ServerInitiatedDirectiveReceiverState`
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguClientKit/Sources/Client/NuguClientDelegate.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiver.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiverState.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
Labels: enhancement

#862 Update `RoutineState`
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineState.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
Labels: capability agent, sample application

#863 Fix to optional `try`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAsset.swift
Labels: capability agent

#859 Dismiss voice chrome when activeSession is nil
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: enhancement

#861 Apply `NuguThemeController` to `AudioDisplayViewPresenter`
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: enhancement, sample application

#864 Pass `requestingFocus` parameter when mic use delegate has been called
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguClientKit/Sources/Client/NuguClientDelegate.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
Labels: enhancement

#865 Call update audio session for proper audio session initialize
  SampleApp/Sources/Manager/NuguCentralManager.swift
Labels: bug

#867 Fix memory issue in NuguOAuthClient
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
  NuguLoginKit/Sources/Grant/AuthorizationCodeGrant.swift
Labels: bug, code quality

#866 Resolve update theme related issues
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  SampleApp/Resources/Base.lproj/Main.storyboard
  SampleApp/Sources/Const/SampleApp.swift
  SampleApp/Sources/Store/UserDefaults+Standard.swift
  SampleApp/Sources/UI/GuideWebViewController.swift
  SampleApp/Sources/UI/IntroViewController.swift
  SampleApp/Sources/UI/MainViewController.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
  SampleApp/Sources/UI/SettingViewController.swift
Labels: bug, sample application

#870 Schedule configuration and getting metadata
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguClientKit/Sources/Configuration/ConfigurationStore.swift
  NuguCore/Sources/Common/NuguServerInfo.swift
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/Network/NetworkError.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug

#871 Cancel `URLSessionDataTask` for server side event after use
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
Labels: bug

#868 Change `DisplayWebView`'s background color when dark mode set
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.swift
Labels: bug

#869 Do not remove voiceChrome from superview if `isHidden` is false
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: bug
