Repository nugu-developers/nugu-ios, pull requests merged in 2021-12, with the labels that each got.

#938 Make `Core` stable on ARC or AudioUnit processing
  Cartfile.resolved
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  SilverTray/Sources/Engine/AudioEngineManager.swift
Labels: bug, crash

#940 Fix issue where the timer was running when it shouldn't be running
  NuguCore/Sources/PlaySync/PlaySyncManager.swift
Labels: bug

#941 Update authorization logic
  NuguClientKit/Sources/Configuration/Configuration.swift
  NuguClientKit/Sources/Configuration/ConfigurationMetadata.swift
  NuguClientKit/Sources/Configuration/ConfigurationStore.swift
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
Labels: enhancement

#943 Remove folder path from exclude.
  Package.swift
Labels: ci/cd

#944 Make `AudioDisplayView` public to be changed by App.
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayViewDelegate.swift
Labels: enhancement

#945 Make `SpeechRecognizerAggregator.Result` public
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorState.swift
Labels: bug
