Repository nugu-developers/nugu-ios, pull requests merged in 2021-03, with the labels that each got.

#766 Add `Contact` object to `MessageCandidatesItem`
  NuguAgents/Sources/CapabilityAgents/Message/MessageCandidatesItem.swift
Labels: capability agent, help wanted, question

#768 Call `VoiceChromePresenterDelegate.voiceChromeChipsDidClick(chips:)` when chips button clicked.
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  NuguUIKit/Sources/VoiceChrome/NuguVoiceChrome.swift
Labels: bug

#772 Fix build errors.
  SampleApp/Podfile.lock
  SampleApp/SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/UI/GuideWebViewController.swift
Labels: bug

#773 Separate Audio hardware issue and format issue
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputError.swift
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputProvider.swift
Labels: code quality

#774 Upgrade `AudioPlayerAgent` to 1.6
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+LyricsEvent.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.xib
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.xib
  NuguUIKit/Sources/AudioDisplayView/Models/AudioPlayer2Template.swift
  NuguUIKit/Sources/AudioDisplayView/Models/AudioPlayerLyricsTemplate.swift
Labels: capability agent

#777 Save the offset of the `MediaPlayer` only if it is not nil.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
Labels: bug

#778 Add `deviceUniqueId` variable to `NuguServiceCookie`
  NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
  NuguServiceKit/Sources/NuguServiceCookie.swift
  SampleApp/Sources/UI/GuideWebViewController.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
Labels: enhancement

#779 Notify the synchronized properties except for the sound layer where the timer is running.
  NuguCore/Sources/PlaySync/PlaySyncManager.swift
Labels: capability agent, enhancement

#780 Fix to handle error for login
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
Labels: bug

#781 Add missing code.
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguClientKit/Sources/Presenter/ControlCenterManager.swift
Labels: bug

#785 Resolve lyrics view related issues
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.swift
Labels: bug

#786 Hide progressview in bar type audio player when isSeekable is false
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.swift
Labels: bug

#787 Implement `getUserInfo()` error handling
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/SettingViewController.swift
Labels: bug, sample application

#788 Change max text line of `AudioPlayer2View`
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.xib
Labels: bug

#789 Set `isScrolling` value as false when automatic scrolling ends
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.swift
Labels: bug

#784 Prepare version 1.0.0 of `NuguAgent`
  NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgent.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentContact.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageCandidatesItem.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallCandidatesItem.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallRecipientIntended.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#790 Implement `PermissionAgent`.
  NuguAgents/Sources/CapabilityAgents/CapabilityAgentCategory.swift
  NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgent.swift
  NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgentProtocol.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/Manager/NuguLocationManager.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#791 Add marquee label (https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/MarqueeLabel.swift)
  .swiftlint.yml
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.xib
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/AudioPlayerBarView.xib
  NuguUIKit/Sources/MarqueeLabel/MarqueeLabel.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#792 Upgrade audio display view
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/AudioPlayerBarView.swift
Labels: enhancement

#793 Remove `poc_end_error.wav` from sample application
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/MediaPlayer/LocalTTSAgent.swift
  SampleApp/Supporting Files/SoundResource/LocalTts/poc_end_error.wav
  nugu-ios.xcodeproj/project.pbxproj
Labels: sample application

#794 Resolve performSegue crash issue
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug, sample application

#795 Check `InteractionControl` when handling `PhoneCall.SendCandidates` directive.
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallCandidatesItem.swift
Labels: bug, capability agent

#796 Resolve `NuguDisplayWebView` memory leak issue
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
Labels: bug

#798 Remove guideTextLabel's text during session has been activated
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: bug

#800 Dismiss voice chrome when any object (including button or web page) has been touched
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: bug, enhancement

#801 Remove APIs used `deprecated` attribute
  JadeMarble/Sources/JadeMarble.swift
  KeenSense/Sources/KeenSense.swift
  NuguAgents/Sources/NuguAgents.swift
  NuguClientKit/Sources/NuguClientKit.swift
  NuguCore/Sources/NuguCore.swift
  NuguServiceKit/Sources/NuguServiceKit.swift
  NuguServiceKit/Sources/NuguServiceWebView.swift
  NuguUIKit/Sources/NuguUIKit.swift
Labels: enhancement

#802 Remove calling `startReceiveServerInitiatedDirective` and `stopReceiveServerInitiatedDirective` function from `SampleApp`.
  NuguClientKit/Sources/Extensions/AuthorizationInfo+Scope.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
Labels: bug

#803 Fixes a bug when casting 'Any' to 'Error'.
  NuguCore/Sources/StreamData/StreamDataRouter.swift
Labels: bug

#804 Fixes a bug when casting 'Any' to 'Error'. (#803)
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  NuguUtils/Sources/TypedNotifyable.swift
Labels: bug
