Repository nugu-developers/nugu-ios, pull requests merged in 2021-05, with the labels that each got.

#826 Add initializer in `AlertsAgentDirectivePayload`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
Labels: capability agent

#827 Implement `RoutineAgent` & `AlertsAgent`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAsset.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsRepeat.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/CapabilityAgentCategory.swift
  NuguAgents/Sources/CapabilityAgents/Routine/Routine+Event.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineError.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineItem.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineState.swift
  NuguAgents/Sources/Extension/TypedNotifyable+post.swift
  NuguClientKit/Sources/Client/NuguClient+Builder.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguCore/Sources/Directive/DirectiveSequenceable.swift
  NuguCore/Sources/Directive/DirectiveSequencer.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#828 Change name to separate between computed and argument values
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/Opus/OpusPlayer.swift
Labels: bug

#824 Change cookie setting methods
  NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
  NuguCore/Sources/Extension/Dictionary+DeepMerge.swift
  NuguServiceKit/Sources/NuguServiceCookie.swift
  NuguServiceKit/Sources/NuguServiceCookieKey.swift
  NuguServiceKit/Sources/NuguServiceCookieValue.swift
  NuguServiceKit/Sources/NuguServiceWebView.swift
  NuguUtils/Sources/Extensions/Container+Merge.swift
  SampleApp/Sources/UI/GuideWebViewController.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#829 Change class to AnyObject
  JadeMarble/Sources/TycheEndPointDetectorEngineDelegate.swift
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngineDelegate.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayDelegate.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectable.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Interaction/InteractionControlManageable.swift
  NuguAgents/Sources/CapabilityAgents/Location/LocationAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Session/SessionManageable.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgentDataSource.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentDelegate.swift
  NuguAgents/Sources/Dialog/DialogAttributeStoreable.swift
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetectorDelegate.swift
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputProviderDelegate.swift
  NuguClientKit/Sources/Client/NuguClientDelegate.swift
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenterDelegate.swift
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenterDelegate.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenterDelegate.swift
  NuguCore/Sources/Authorization/AuthorizationStoreDelegate.swift
  NuguCore/Sources/Authorization/AuthorizationStoreable.swift
  NuguCore/Sources/Context/ContextManageable.swift
  NuguCore/Sources/Focus/FocusChannelDelegate.swift
  NuguCore/Sources/Focus/FocusDelegate.swift
  NuguCore/Sources/Focus/FocusManageable.swift
  NuguCore/Sources/MediaPlayer/MediaPlayable.swift
  NuguCore/Sources/MediaPlayer/MediaPlayerDelegate.swift
  NuguCore/Sources/Network/Api/MultiPartProcessable.swift
  NuguCore/Sources/StreamData/UpstreamDataSendable.swift
  NuguServiceKit/Sources/NuguServiceWebJavascriptDelegate.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayViewDelegate.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/AudioPlayerBarViewDelegate.swift
Labels: code quality

#832 Update `AlertsAgent`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAsset.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsRepeat.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  NuguUtils/Sources/Extensions/KeyedDecodingContainerExtension.swift
Labels: capability agent

#834 Make public init method in `AlertsAgentDirectivePayload`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
Labels: capability agent

#837 Process Nudge scene
  NuguAgents/Sources/CapabilityAgents/Nudge/NudgeAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguClientKit/Sources/Business/DialogStateAggregator.swift
Labels: bug

#839 Restore chipsItems removing logic
  NuguClientKit/Sources/Business/DialogStateAggregator.swift
Labels: bug

#840 Fix TextCodes to suitable for Nimble latest version
  Cartfile
  Cartfile.resolved
  NuguTests/Mock/MockDirectiveSequencer.swift
  NuguTests/NuguAgents/ASRAgentSpec.swift
  NuguTests/NuguAgents/AudioPlayerAgentSpec.swift
  NuguTests/NuguAgents/DisplayAgentSpec.swift
  NuguTests/NuguAgents/ExtensionAgentSpec.swift
  NuguTests/NuguAgents/LocationAgentSpec.swift
  NuguTests/NuguAgents/SoundAgentSpec.swift
  NuguTests/NuguAgents/SystemAgentSpec.swift
  NuguTests/NuguAgents/TTSAgentSpec.swift
  NuguTests/NuguAgents/TextAgentSpec.swift
Labels: ci/cd

#841 Add `name` field in `AlertsAgentContext` and `SetAlert` directive pay…
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
Labels: capability agent

#843 Add `referrerDialogRequestId` in `AlertsAgent`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
Labels: bug, capability agent

#845 Present Nudge chips during presenting speaking state
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: bug

#844 Clear server policies after stopping receiving `Server Initiated Directive'
  NuguCore/Sources/StreamData/ServerSideEventReceiver.swift
Labels: backend

#846 Change `class` to `AnyObject`
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguClientKit/Sources/Audio/AudioSessionManageable.swift
  NuguClientKit/Sources/Audio/AudioSessionManagerDelegate.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatable.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorDelegate.swift
  NuguCore/Sources/Context/ContextInfoProvidable.swift
Labels: invalid

#851 Remain last server policy to use next time.
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiver.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
Labels: backend

#850 Fix lint warnings
  KeenSense/Sources/KeenSense.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRState.swift
  NuguCore/Sources/MediaPlayer/MediaAVPlayerItem.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  NuguServiceKit/Sources/NuguServiceCookieKey.swift
  NuguUIKit/Sources/Button/NuguButton.swift
Labels: code quality

#849 Change `TycheKeywordDetector`'s notification mechanism from `Delegate…
  KeenSense/Sources/KeenSense.swift
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngine+State.swift
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngine.swift
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngineDelegate.swift
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetector.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: code quality

#852 Remove codes supporting lower than iOS 12.0 version
  NuguLoginKit/Sources/Grant/AuthorizationCodeGrant.swift
  NuguLoginKit/Sources/Handler/SFAuthenticationOAuthHandler.swift
  NuguLoginKit/Sources/Handler/SFSafariOAuthHandler.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: drop

#857 Add `state` for current routine state
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentProtocol.swift
Labels: capability agent
