Repository nugu-developers/nugu-ios, pull requests merged in 2021-02, with the labels that each got.

#729 Write code-documentation
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentPlaylist.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgentSong.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentContact.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageCandidatesItem.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageRecipientIntended.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageToSendItem.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallCandidatesItem.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallErrorCode.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallIntent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallRecipientIntended.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallState.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallType.swift
  NuguAgents/Sources/CapabilityAgents/Session/Session.swift
  NuguAgents/Sources/CapabilityAgents/Session/SessionAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Utility/UtilityAgentProtocol.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: code quality

#717 Fix `SwiftLint` warnings.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgent.swift
  NuguAgents/Sources/CapabilityAgents/Interaction/InteractionControlManager.swift
  NuguAgents/Sources/CapabilityAgents/Session/SessionManager.swift
  NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguAgents/Sources/Extension/TypedNotifyable+post.swift
  NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
  NuguClientKit/Sources/Business/DialogStateAggregator.swift
  NuguCore/Sources/Directive/DirectiveSequencer.swift
  NuguCore/Sources/Extension/TypedNotification+post.swift
  NuguCore/Sources/MediaPlayer/MediaAVPlayerItem.swift
  NuguCore/Sources/PlaySync/PlaySyncManager.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  NuguCore/Sources/StreamData/StreamDataState.swift
  NuguServiceKit/Sources/NuguServiceWebView.swift
  SampleApp/Sources/UI/Views/NuguWebView.swift
Labels: code quality

#716 Handle `InteractionControl` field from `Text.TextRedirect`.
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentRedirectPayload.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguTests/NuguAgents/TextAgentSpec.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#730 Remove Observer-Delegate bridge
  NuguCore/Sources/MediaPlayer/MediaAVPlayerItem.swift
  NuguCore/Sources/MediaPlayer/MediaAVPlayerItemDelegate.swift
  NuguCore/Sources/MediaPlayer/MediaPlayer.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: code quality

#720 Rename extended function of `NuguOAuthClient`
  NuguClientKit/Sources/Extensions/NuguOAuthClient+Convenience.swift
  SampleApp/Resources/Base.lproj/Main.storyboard
  SampleApp/Sources/Const/SampleApp.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/Store/UserDefaults+Standard.swift
  SampleApp/Sources/UI/IntroViewController.swift
Labels: code quality

#732 Fix `SwiftLint` warnings.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/Event/Eventable.swift
  NuguAgents/Sources/Extension/Attachable+makeAttachmentMessage.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguClientKit/Sources/Configuration/ConfigurationMetadata.swift
  NuguCore/Sources/MediaPlayer/MediaPlayer.swift
Labels: code quality

#735 Remove `refreshToken` validation when login anonymously.
  SampleApp/Sources/Manager/NuguCentralManager.swift
Labels: bug

#737 Implement mock delegation in test code for capability agent.
  NuguTests/NuguAgents/AudioPlayerAgentSpec.swift
  NuguTests/NuguAgents/DisplayAgentSpec.swift
  NuguTests/NuguAgents/TextAgentSpec.swift
Labels: code quality

#738 Move `UITapGestureRecognizer` from `Application` to `VoiceChromePresenter` for convenience.
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenterDelegate.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: sample application

#733 Support dynamic allocation of resource server URL.
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiver.swift
Labels: bug

#741 Add `WebTheme` options in 'NuguLoginKit'
  NuguClientKit/Sources/Configuration/Configuration.swift
  NuguClientKit/Sources/Extensions/NuguOAuthClient+Convenience.swift
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
  NuguLoginKit/Sources/Business/WebTheme.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: backend, enhancement

#734 Fix crash in UserDefaults when setting a nil value.
  SampleApp/Sources/PropertyWrappers/UserDefaultsWrapper.swift
Labels: bug

#749 Remove `watermarkLabel` and `textInputTextField` to minimize sample application.
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  SampleApp/Resources/Base.lproj/Main.storyboard
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: code quality, sample application

#750 Post `AudioPlayer.Duration` as `truncatedSeconds`
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: bug

#751 Implement required APIs on Subclassing `InputStream`
  NuguUtils/Sources/DataBoundInputStream.swift
Labels: bug

#752 Put the resources for signal processing into the frameworks
  JadeMarble.podspec
  JadeMarble/Resources/skt_epd_model.raw
  JadeMarble/Sources/TycheEndPointDetectorEngine.swift
  KeenSense.podspec
  KeenSense/Resources/skt_trigger_am_aria.raw
  KeenSense/Resources/skt_trigger_am_tinkerbell.raw
  KeenSense/Resources/skt_trigger_search_aria.raw
  KeenSense/Resources/skt_trigger_search_tinkerbell.raw
  KeenSense/Sources/KeenSense.swift
  KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngine.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASROptions.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/ClientEndPointDetector.swift
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetector.swift
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordSource.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  README.md
  SampleApp/Podfile.lock
  SampleApp/SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Const/Keyword.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/SettingViewController.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#755 Add `MessageAgent` to `NuguClient` and Its builder
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputProvider.swift
  NuguClientKit/Sources/Client/NuguClient+Builder.swift
  NuguClientKit/Sources/Client/NuguClient.swift
Labels: capability agent

#754 Add `togglePlayAndPauseCommand` target for a wired earset
  SampleApp/Sources/Manager/NuguDisplayPlayerController.swift
Labels: enhancement
