Repository nugu-developers/nugu-ios, pull requests merged in 2021-04, with the labels that each got.

#808 `ASRAgent` 1.6 (upgrade capability-agent)
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRError.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRExpectSpeech.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: capability agent

#812 Add `Nudge` type chips button for `VoiceChrome`.
  NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgentItem.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  NuguUIKit/Sources/Chips/NuguChipsButton.swift
  SampleApp/Podfile.lock
Labels: capability agent

#809 Disable `UITableViewCell` for wake up word when `NUGU` service disabled.
  SampleApp/Sources/UI/SettingViewController.swift
  SampleApp/Sources/UI/Views/SettingTableViewCell.swift
Labels: sample application

#814 Add top margin to display web view presenter
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.swift
Labels: enhancement

#815 Apply autolayout to close button
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.swift
Labels: bug

#816 Support lyricsView rotation
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.xib
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.swift
Labels: enhancement

#817 Resolve audio display view issues
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.xib
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.xib
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/AudioPlayerBarView.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/DisplayIdleBar.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/DisplayTitleView.swift
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.swift
  NuguUIKit/Sources/MarqueeLabel/MarqueeLabel.swift
Labels: bug

#818 Resolve full lyrics view crash issue
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.swift
Labels: bug

#819 Change audio player view layout
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.xib
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer2View.xib
Labels: bug

#820 Fixes a key for decoding `listenTimeoutBeep`
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRExpectSpeech.swift
Labels: bug

#821 Implement `RoutineAgent`
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/CapabilityAgentCategory.swift
  NuguAgents/Sources/CapabilityAgents/Routine/Routine+Event.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineError.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineItem.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineState.swift
  NuguAgents/Sources/Extension/TypedNotifyable+post.swift
  NuguClientKit/Sources/Client/NuguClient+Builder.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguCore/Sources/Directive/DirectiveSequenceable.swift
  NuguCore/Sources/Directive/DirectiveSequencer.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#825 Add completion closure to `startListeningWithTrigger` to catch the er…
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatable.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorError.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: code quality
