Repository nugu-developers/nugu-ios, pull requests merged in 2021-09, with the labels that each got.

#918 Add initializer in `EventIdentifier`
  NuguAgents/Sources/Event/EventIdentifier.swift
Labels: bug

#920 Set default channel count as 1 when returned value is 0
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputConst.swift
  SampleApp/Sources/UI/SettingViewController.swift
Labels: bug

#921 Resolve `SpeechRecognizerAggregator` and `VoiceChromePresenter` issues
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorState.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug

#922 Update to call `completion` after processing `close` directive
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent.swift
  SampleApp/Podfile.lock
Labels: capability agent

#923 Support suitable `AudioPlayerView` in iPad and Mac catalyst
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.xib
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: enhancement, sample application

#924 Fix missing context payload in `RoutineAgent`
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
Labels: bug, capability agent

#925 Hide lyrics stack view when there are no lyrics to show
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
Labels: bug

#926 Dismiss VoiceChrome when SpeechRecognizerAggregatorError occurs
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRError.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: bug

#927 Bug/lyric view and voice chrome issue
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorState.swift
  NuguUIKit/Sources/AudioDisplayView/AudioPlayer1View.swift
  NuguUIKit/Sources/AudioDisplayView/ComponentViews/FullLyricsView.xib
Labels: bug
