Repository nugu-developers/nugu-ios, pull requests merged in 2021-07, with the labels that each got.

#876 Set theme initial value when `NuguThemeController` has been injected
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguClientKit/Sources/Presenter/VoiceChromePresenter.swift
Labels: bug

#880 Add `TabExtension` to `DisplayAgent` (upgrade to v1.8)
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent.swift
Labels: capability agent

#877 Add startMicWorkItemQueue for sync execute of workItem
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetector.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  SampleApp/Sources/UI/MainViewController.swift
Labels: bug

#882 Add `ignoreSendingResumeEvent` variable
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: bug

#883 Send `dialog_request_id` when loading `DisplayWebView`
  NuguClientKit/Sources/Presenter/DisplayWebViewPresenter.swift
  NuguUIKit/Sources/DisplayView/NuguDisplayWebView.swift
Labels: enhancement

#885 Fix the state change from `.playing` to `.playing` in `RoutineAgent`
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug, capability agent

#884 Send stop / start event instead of resume event
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: bug

#888 Refactor `NuguClientKit` and `MainViewController`
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorDelegate.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguClientKit/Sources/Client/NuguClientDelegate.swift
  SampleApp/Resources/Base.lproj/Main.storyboard
  SampleApp/Sources/AppDelegate.swift
  SampleApp/Sources/Const/SampleApp.swift
  SampleApp/Sources/Manager/NuguCentralManager.swift
  SampleApp/Sources/UI/GuideWebViewController.swift
  SampleApp/Sources/UI/MainViewController.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
Labels: code quality, sample application

#891 Fix podspec issue
  NuguObjcUtils.podspec
  OpusSDK.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug

#889 Fix missing initializer function in `MessageAgentContext`
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgentContext.swift
Labels: bug, capability agent

#892 Remove useless `preserved_path` statement
  JadeMarble.podspec
  KeenSense.podspec
Labels: bug, ci/cd
