Repository nugu-developers/nugu-ios, pull requests merged in 2022-05, with the labels that each got.

#960 Add directive(ExpectTyping) handler to TextAgent
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/Session/SessionManager.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentExpectTyping.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentRequestType.swift
  NuguAgents/Sources/Dialog/DialogAttributeStore.swift
  NuguAgents/Sources/Dialog/DialogAttributeStoreable.swift
  NuguClientKit/Sources/Client/NuguClient+Builder.swift
Labels: capability agent

#967 Add `prepared` to `StreamDatastate`
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguCore/Sources/StreamData/StreamDataState.swift
Labels: enhancement

#971 S.I.D. Don't wait for connectivity and Reconnect when it is available.
  NuguCore/Sources/Network/Api/ClientSideLoadBalanceState.swift
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiver.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiverState.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
Labels: bug

#973 Add 'jayce1116' to CODEOWNER
  .github/CODEOWNERS
Labels: ci/cd

#976 Set error state to AsrResult rather then reset to nil When it could not prepared.
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
Labels: enhancement

#980 Release focus when the audio player is stopped only.
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: bug
