Repository nugu-developers/nugu-ios, pull requests merged in 2022-11, with the labels that each got.

#1012 Send actionTimeout event on designated time
  NuguAgents/Sources/CapabilityAgents/Routine/Routine+Event.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineItem.swift
Labels: enhancement

#1013 Update alert agent
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsRepeat.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
Labels: capability agent

#1014 Ignore stop event after action move event
  NuguAgents/Sources/CapabilityAgents/Routine/Routine+Event.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineItem.swift
Labels: bug

#1016 Move to countable index when received to move directive
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1017 Remove `active` checking logic on `startMicInputProvider`.
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
Labels: bug

#1019 Set mute delay after actions If Directives contains `Apollo.Reactive` and not `TTS.Speak`
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: enhancement

#1018 Nudge context를 보내는 로직 수정
  NuguAgents/Sources/CapabilityAgents/Nudge/NudgeAgent.swift
  NuguCore/Sources/PlaySync/PlaySyncManager.swift
Labels: bug

#1020 연속된 Move Event가 발생할 경우 Interrupt Event 무시하도록 수정
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1022 Mic를 열지 못한 상황과 권한이 없는 상황을 분리
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputError.swift
  NuguClientKit/Sources/Audio/MicInputProvider/MicInputProvider.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatable.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatorError.swift
Labels: enhancement

#1021 Update Alert Interface version to 1.5
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgentDirectivePayload.swift
Labels: enhancement, capability agent

#1023 `stopPlay`에서 property를 지정하지 않더라도 overlay는 pop되지 않도록 수정
  NuguCore/Sources/PlaySync/PlaySyncManager.swift
Labels: capability agent
