Repository nugu-developers/nugu-ios, pull requests merged in 2022-08, with the labels that each got.

#992 Pass hard-coded framework version on SPM
  NuguCore/Sources/Network/NetworkConst.swift
Labels: bug

#990 add `RoutineAgentSpec`
  NuguCore/Sources/Directive/DirectiveCancelPolicy.swift
  NuguCore/Sources/Directive/DirectiveHandleResult.swift
  NuguTests/Dummy/DummyASRAgent.swift
  NuguTests/Dummy/DummyStreamDataRouter.swift
  NuguTests/Fake/FakeContextManager.swift
  NuguTests/Fake/FakeDirectiveSequencer.swift
  NuguTests/Mock/MockTextAgent.swift
  NuguTests/Mock/MockUpstreamDataSender.swift
  NuguTests/NuguAgents/RoutineAgentTests.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#993 Remove `Attributes` when the `ASR` and `TextInput` process are done.
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
Labels: bug, capability agent

#994 Make `version` accessible
  NuguCore/Sources/Network/NetworkConst.swift
  NuguCore/Sources/NuguCore.swift
Labels: enhancement

#998 fix `NuguAgents` build error
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug
