Repository nugu-developers/nugu-ios, pull requests merged in 2022-09, with the labels that each got.

#999 Replace `OperationQueue` to `DispatchQueue`
  NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetector.swift
  NuguClientKit/Sources/Configuration/ConfigurationStore.swift
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  SampleApp/Podfile.lock
  SilverTray/Sources/DataStreamPlayer.swift
  SilverTray/Sources/Engine/AudioEngineManager.swift
Labels: bug

#995 add `Events`, `SUSPENDED` states
  NuguAgents/Sources/CapabilityAgents/Routine/Routine+Event.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineItem.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineState.swift
  NuguCore/Sources/Directive/DirectiveCancelPolicy.swift
  NuguCore/Sources/Directive/DirectiveHandleResult.swift
  NuguTests/Dummy/DummyASRAgent.swift
  NuguTests/Dummy/DummyStreamDataRouter.swift
  NuguTests/Fake/FakeContextManager.swift
  NuguTests/Fake/FakeDirectiveSequencer.swift
  NuguTests/Mock/MockTextAgent.swift
  NuguTests/Mock/MockUpstreamDataSender.swift
  NuguTests/NuguAgents/RoutineAgentTests.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#1000 Change api argument name from messageId to key
  Cartfile.resolved
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentProtocol.swift
  NuguAgents/Sources/Dialog/DialogAttributeStore.swift
  NuguAgents/Sources/Dialog/DialogAttributeStoreable.swift
  NuguTests/Mock/MockDialogAttributeStore.swift
  NuguTests/NuguAgents/Dialog/DialogAttributeStoreSpec.swift
Labels: enhancement

#1002 Make `InterfactionControl` payload not to `Data` but `Dictionary`
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Message/MessageAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
Labels: crash

#1003 Version Update (1.7.7)
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguClientKit.podspec
  NuguCore.podspec
  NuguLoginKit.podspec
  NuguObjcUtils.podspec
  NuguServiceKit.podspec
  NuguUIKit.podspec
  NuguUtils.podspec
  OpusSDK.podspec
  SilverTray.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd
