Repository nugu-developers/nugu-ios, pull requests merged in 2022-12, with the labels that each got.

#1025 AudioEngine에 대한 시나리오는 `AudioEngineConfigurationChanged`를 구독하는 각 observer가 처리하도록 수정
  SilverTray/Sources/Engine/AudioEngineManager.swift
Labels: crash

#1024 `Move` Action 시, routine state를 playing으로 변경 및 handlingDirectives 초기화
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1026 `AudioEngineObservers` insert/remove와 `AVAudioEngine` start/stop이 serial하게 이루어지도록 수정
  SilverTray/Sources/DataStreamPlayer.swift
  SilverTray/Sources/Engine/AudioEngineManager.swift
Labels: bug, crash

#1027 `AVAudioEngine` nodes를 `attach`/`detach`할 때 예외처리
  SilverTray/Sources/DataStreamPlayer.swift
  SilverTray/Sources/Engine/AudioEngineManager.swift
Labels: crash

#1028 `AVAudioEngine`이 준비될 때까지 player의 동작을 늦춘다.
  SilverTray/Sources/DataStreamPlayer.swift
Labels: bug

#1029 AudioPlayerAgent handlePlay의 finish 시점 변경
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerResult.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#1031 AudioEngine용 Jitter size를 2.5배 늘리고 queue priority를 `userInitiated`로 상향
  SilverTray/Sources/DataStreamPlayer.swift
Labels: enhancement
