Repository nugu-developers/nugu-ios, pull requests merged in 2023-08, with the labels that each got.

#1072 Audio session deactivation을 2초 지연 후 수행
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguClientKit/Sources/Client/NuguClientConst.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement

#1073 requestTextInput Method 수정
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: capability agent

#1074 루틴 액션을 실행하는 중 오류가 발생하면 다음 액션을 이동하지 않고 pause 상태로 이동하게 변경
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1075 ActionTriggerTimout를 actionWorkItem으로 일괄 관리하도록 변경
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1077 Routine에서 현재 실행 중인 actiondml directive가 모두 종료되었을 때 playing 상태가 아니라면 다음 액션을 실행하지 않도록 변경
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1076 SystemAgent 의 Nodirective Directive를 notification에 추가
  NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
Labels: capability agent
