Repository nugu-developers/nugu-ios, pull requests merged in 2023-04, with the labels that each got.

#1041 Release to `1.8.1`
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayer1Template.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayerPlaylist.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayerUpdateMetadataPayload.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlaylistEvent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentRequestType.swift
  NuguClientKit.podspec
  NuguClientKit/Sources/Audio/ControlCenterManager.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguCore.podspec
  NuguCore/Sources/NuguCore.swift
  NuguLoginKit.podspec
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
  NuguObjcUtils.podspec
  NuguServiceKit.podspec
  NuguUIKit.podspec
  NuguUtils.podspec
  OpusSDK.podspec
  SilverTray.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd

#1042 loginKit 의 presentAuthorize 에서 deviceUniqueId 를 "deviceUniqueId" 잘 못 넘기고 있는 이슈 수정
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
Labels: bug

#1045 직접 다루지 않는 cancelAll이 들어왔을 때 stop이 아닌, interrupt 상태로 변경
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
Labels: bug

#1046 Update rx swift
  Cartfile
  Cartfile.resolved
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayManager.swift
  NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent.swift
  NuguAgents/Sources/Extension/ContextManager+Rx.swift
  NuguClientKit.podspec
  NuguCore.podspec
  NuguCore/Sources/Context/ContextManager.swift
  NuguCore/Sources/Extension/URLRequest+Rx.swift
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/StreamData/ServerSideEventReceiver.swift
  NuguLoginKit.podspec
  NuguServiceKit.podspec
  NuguUIKit.podspec
  NuguUtils.podspec
  SampleApp/Podfile.lock
  nugu-ios.xcodeproj/project.pbxproj
Labels: enhancement
