Repository nugu-developers/nugu-ios, pull requests merged in 2023-01, with the labels that each got.

#1033 Update version to `1.8.1`
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguClientKit.podspec
  NuguCore.podspec
  NuguCore/Sources/NuguCore.swift
  NuguLoginKit.podspec
  NuguObjcUtils.podspec
  NuguServiceKit.podspec
  NuguUIKit.podspec
  NuguUtils.podspec
  OpusSDK.podspec
  SilverTray.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd

#1034 Add Playlist Response Model In AudioPlayerAgent
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayer1Template.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayerPlaylist.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayerUpdateMetadataPayload.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlaylistEvent.swift
  NuguClientKit/Sources/Audio/ControlCenterManager.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#1035 Insert additional queries to data json in presenting authorize
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
Labels: enhancement

#1036 Deprecate `TextAgentRequestType`
  NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Text/TextAgentRequestType.swift
  NuguClientKit/Sources/Client/NuguClient.swift
Labels: enhancement
