Repository nugu-developers/nugu-ios, pull requests merged in 2023-05, with the labels that each got.

#1047 update version to `1.8.2`
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguClientKit.podspec
  NuguCore.podspec
  NuguCore/Sources/NuguCore.swift
  NuguLoginKit.podspec
  NuguObjcUtils.podspec
  NuguServiceKit.podspec
  NuguUIKit.podspec
  NuguUtils.podspec
  OpusSDK.podspec
  SilverTray.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd

#1048 Release to `1.8.2`
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguAgents/Sources/CapabilityAgents/Location/LocationAgent.swift
  NuguAgents/Sources/CapabilityAgents/Location/LocationAgentDelegate.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguClientKit.podspec
  NuguCore.podspec
  NuguCore/Sources/NuguCore.swift
  NuguLoginKit.podspec
  NuguLoginKit/Sources/Business/NuguOAuthClient.swift
  NuguObjcUtils.podspec
  NuguServiceKit.podspec
  NuguTests/NuguAgents/LocationAgentSpec.swift
  NuguUIKit.podspec
  NuguUtils.podspec
  OpusSDK.podspec
  SilverTray.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd

#1049 update version to `1.9.0`
  JadeMarble.podspec
  KeenSense.podspec
  NuguAgents.podspec
  NuguClientKit.podspec
  NuguCore.podspec
  NuguCore/Sources/NuguCore.swift
  NuguLoginKit.podspec
  NuguObjcUtils.podspec
  NuguServiceKit.podspec
  NuguUIKit.podspec
  NuguUtils.podspec
  OpusSDK.podspec
  SilverTray.podspec
  TycheSDK.podspec
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd

#1051 Add Image Interface
  NuguAgents/Sources/CapabilityAgents/Image/Image+Event.swift
  NuguAgents/Sources/CapabilityAgents/Image/ImageAgent.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#1052 Apply `Messenger Interface` v1.1
  NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgent+Event.swift
  NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgent.swift
  NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgentEventPayload.swift
Labels: capability agent

#1054 Remove `Quick/Nimble`
  .github/workflows/test_pull_request.yml
  Cartfile.private
  Cartfile.resolved
  NuguTests/Dummy/DummyASRAgent.swift
  NuguTests/Dummy/DummyStreamDataRouter.swift
  NuguTests/Fake/FakeContextManager.swift
  NuguTests/Fake/FakeDirectiveSequencer.swift
  NuguTests/Info.plist
  NuguTests/Mock/MockContextManager.swift
  NuguTests/Mock/MockDialogAttributeStore.swift
  NuguTests/Mock/MockDirectiveSequencer.swift
  NuguTests/Mock/MockFocusManager.swift
  NuguTests/Mock/MockInteractionControlManager.swift
  NuguTests/Mock/MockPlaySyncManager.swift
  NuguTests/Mock/MockSessionManager.swift
  NuguTests/Mock/MockStreamDataRouter.swift
  NuguTests/Mock/MockTextAgent.swift
  NuguTests/Mock/MockUpstreamDataSender.swift
  NuguTests/NuguAgents/ASRAgentSpec.swift
  NuguTests/NuguAgents/AudioPlayerAgentSpec.swift
  NuguTests/NuguAgents/Dialog/DialogAttributeStoreSpec.swift
  NuguTests/NuguAgents/DisplayAgentSpec.swift
  NuguTests/NuguAgents/ExtensionAgentSpec.swift
  NuguTests/NuguAgents/LocationAgentSpec.swift
  NuguTests/NuguAgents/RoutineAgentTests.swift
  NuguTests/NuguAgents/SoundAgentSpec.swift
  NuguTests/NuguAgents/SystemAgentSpec.swift
  NuguTests/NuguAgents/TTSAgentSpec.swift
  NuguTests/NuguAgents/TextAgentSpec.swift
  NuguTests/NuguCore/CryptoUtilSpec.swift
  NuguTests/NuguCore/FocusManagerSpec.swift
  NuguTests/NuguCore/SessionManagerSpec.swift
  NuguTests/NuguCore/TimeIntervallicTests.swift
  NuguTests/NuguCore/UpstreamSpec.swift
  NuguTests/NuguCore/XDirectiveSequencerTest.swift
  nugu-ios.xcodeproj/project.pbxproj
  nugu-ios.xcodeproj/xcshareddata/xcschemes/NuguTests.xcscheme
Labels: ci/cd

#1053 sendImage에 attachment 추가
  NuguAgents/Sources/CapabilityAgents/Image/Image+Event.swift
  NuguAgents/Sources/CapabilityAgents/Image/ImageAgent.swift
  NuguAgents/Sources/Extension/Attachable+Convenience.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#1055 `NuguClient` 내부에 `MessengerAgent`, `ImageAgent` 추가
  NuguAgents/Sources/CapabilityAgents/Image/ImageAgent.swift
  NuguAgents/Sources/CapabilityAgents/Image/ImageAgentProtocol.swift
  NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgent.swift
  NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgentProtocol.swift
  NuguClientKit/Sources/Client/NuguClient+Builder.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: capability agent

#1056 Directive Header에 messageTimestamp추가
  NuguCore/Sources/StreamData/Model/Downstream.swift
Labels: enhancement
