Repository nugu-developers/nugu-ios, pull requests merged in 2023-10, with the labels that each got.

#1085 직렬화 시도할 때 발생할 수 있는 OBJC Exception 처리
  NuguCore/Sources/StreamData/Model/Upstream.swift
  Package.swift
Labels: enhancement

#1088 Client side load balance 주소 지정
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
Labels: enhancement

#1087 `startListening`, `startListeningWithTirgger`, `stopListening`의 동작이 원자성을 가지도록 수정
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatable.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
Labels: bug

#1086 Server sent event (directive) 시작/종료에 대한 순서를 보장한다
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
Labels: bug

#1093 startListening에 있는 semaphore제거
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
Labels: bug

#1094 SessionManager에서 session을 set할 때 activeList에 존재하는 session일 경우 로직 변경
  NuguAgents/Sources/CapabilityAgents/Session/SessionManager.swift
Labels: bug

#1098 Develop/1.9.1
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayDelegate.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/AudioPlayerDisplayManager.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Display/Models/AudioPlayer2Template.swift
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlaylistEvent.swift
  NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentContext.swift
  NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDirectivePayload.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineExecuter.swift
  NuguAgents/Sources/CapabilityAgents/Session/SessionManager.swift
  NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
  NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentProtocol.swift
  NuguClientKit/Sources/Audio/AudioSessionManager.swift
  NuguClientKit/Sources/Audio/AudioSessionManagerDelegate.swift
  NuguClientKit/Sources/Audio/ControlCenterManager.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregatable.swift
  NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
  NuguClientKit/Sources/Client/NuguClient.swift
  NuguClientKit/Sources/Client/NuguClientConst.swift
  NuguClientKit/Sources/Client/NuguClientDelegate.swift
  NuguClientKit/Sources/Presenter/AudioDisplayViewPresenter.swift
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/StreamData/Model/Upstream.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  Package.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: ci/cd

#1099 URLSessionTask과 관계 없이 ResourceLoader가 원하는 데이터를 전달할 수 있도록 수정
  NuguCore/Sources/MediaPlayer/MediaPlayer.swift
Labels: bug

#1096 오디오플레이어 보여지는 시점 변경
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: bug

#1102 Playlist Token Key 값 수정
  NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
Labels: capability agent
