Repository nugu-developers/nugu-ios, pull requests merged in 2024-02, with the labels that each got.

#1127 RoutineAgentDelegate 업데이트
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
  NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgentDelegate.swift
  SampleApp/Sources/UI/NuguServiceWebViewController.swift
Labels: capability agent

#1129 AudioFocus Release(Deactivate)가 이미 예정되어있으면 다시 등록하지 않도록 처리
  NuguClientKit/Sources/Client/NuguClient.swift
Labels: bug

#1126 `ServerSentEvent`의 state와 PingDisposable의 Race condition 해결
  NuguClientKit/Sources/Client/NuguClientDelegate.swift
  NuguCore/Sources/Network/Api/NuguApiProvider.swift
  NuguCore/Sources/Network/Api/ServerSentEventProcessor.swift
  NuguCore/Sources/StreamData/ServerSentEventReceiver.swift
  NuguCore/Sources/StreamData/ServerSentEventReceiverState.swift
  NuguCore/Sources/StreamData/StreamDataRouter.swift
  nugu-ios.xcodeproj/project.pbxproj
Labels: bug, crash

#1130 ServerSentEventReceiver 크래시 수정
  NuguCore/Sources/StreamData/ServerSentEventReceiver.swift
Labels: bug

#1131 ControlCenter에서 offset드래그시 NowPlayingInfo의 offset도 업데이트하도록 수정
  NuguClientKit/Sources/Audio/ControlCenterManager.swift
Labels: bug
